### ISSUE TITLE
5xx status codes ranges are not supported

### ISSUE THREAD

**Issue by malkevych** [byu-oit/openapi-enforcer#103]
When I define my status code with code like 5xx I receive error:

[ EnforcerException: One or more errors exist in the OpenApi definition
    at: paths
      at: /v1/leads > post > responses
        Property not allowed: 5xx

**Comment by Gi60s** [comment]
Nice catch. I hadn't thought of this scenario. I'll get working on a fix.

**Comment by Gi60s** [comment]
@malkevych Sorry about the wait on this one. Looking at the spec OpenAPI version 2.0 does not support wildcard response codes, but 3.0.0 and newer do. Make sure that you're following the spec there. Also, the `response` function used to validate and serialize responses did not support wildcard response codes but I have now added that in.

These changes have been published to npm as version `1.13.1`.

I hope that resolves the issue for you. Let me know if there is anything else.

Thank you.
