### ISSUE TITLE
Object's properties not deserialized correctly when using allOf inside of allOf

### ISSUE THREAD

**Issue by Kristof-Mattei** [byu-oit/openapi-enforcer#111]
Here I am again! This time with an issue where I do have a solution for, but I am trying to understand whether it should work without my solution.

Let's get started with our schema:

```yaml
openapi: 3.0.3
info:
  title: Test
  version: 0.0.1
  description: description
  termsOfService: "https://terms"
  contact:
    name: test
    url: "http://url"
    email: test@test.com
servers:
  - url: "https://server"
paths: {}
components:
  schemas:
    Object1: 
      allOf: 
        - $ref: "#/components/schemas/Object2" 
        - type: object
          required:
            - date
          properties:
            date:
              type: string
              format: date-time

    Object2: 
      # type: object # THIS LINE
      allOf: 
       - $ref: "#/components/schemas/Object3" 
       - $ref: "#/components/schemas/Object4" 

    Object3: 
      properties:
        foo: 
          type: string
        
    Object4: 
      properties:
        bar: 
          type: string
```

And our test code:

```javascript
const Enforcer = require('openapi-enforcer')

Enforcer("./reproduce.yaml", { fullResult: true }).then(openapi => {
    const deserialized = openapi.value.components.schemas.Object1.deserialize({
        foo: "test",
        bar: "test",
        date: "2000-01-01T00:00:00.000Z"
    })

    const validated = openapi.value.components.schemas.Object1.validate(deserialized.value);

    console.log(validated);
});
```

When we run this we get

```bash
$ node ./index.js
[ EnforcerException: Invalid value
    Did not validate against all schemas
      at: 1 > date
        Expected a valid date object. Received: "2000-01-01T00:00:00.000Z" ]
```

However, in our schema, in `Object2` you'll notice that I've commented out the `type: object`. That was on purpose. I originally missed that, because when I create a schema called `Foo` with `properties` `openapi-enforcer` deduces that it is of `type: object`.

With `Object2` this is not the case. I explicitely need to specify `type: object` otherwise the deserializers of `Object1.allOf[1]` don't run, because `Object1.allOf[0]` wasn't of `type: object`: https://github.com/byu-oit/openapi-enforcer/blob/e29d5b35bd8fd55f065d7476907234ad51cba21f/src/schema/deserialize.js#L50

Now, I see 3 solutions, in order of what I think is more correct to less correct.:

1. When deserializing the schema and the code encounters an `allOf`, it checks for the presense of `type: object` as a sibling. If not present, it adds it, somewhere around here: https://github.com/byu-oit/openapi-enforcer/blob/e29d5b35bd8fd55f065d7476907234ad51cba21f/src/enforcers/Schema.js#L256
1. We add `type: object` to our `Object2` and be explicit. 
1. When deserializing the data and we hit the code specified above we update the `if` clause as follows: `if (schema.allOf[0].type === 'object' || !!schema.allOf[0].allOf)`

I've spent some time thinking if it's possible to create a schema with `allOf` and its `type` not to be `object`... and I cannot come up with anything.

E.g.: 
```yaml
# ...
components:
  schemas:
    Object1: 
      # type: object # What else?
      allOf: 
       - $ref: "#/components/schemas/Object2" 
       - $ref: "#/components/schemas/Object3" 

    Object2: 
        type: string
        
    Object3: 
      type: string

```

Like what would `Object1` really be?

Edit: I've also created a repl.it with everything inline to easier validation: https://repl.it/@KristofMattei/ViciousCyberKeygens#index.js

**Comment by Gi60s** [comment]
I've spent a lot of time trying to solve this and the conclusion I've come to is that this might need to wait for Enforcer version 2 to fix. For now the best solution is probably to create a schema that includes all 3 allOf schemas.

I created an `ObjectX` schema below as an example.

```yml
components:
  schemas:
    ObjectX:
      allOf: 
        - $ref: "#/components/schemas/Object2" 
       - $ref: "#/components/schemas/Object3" 
       - $ref: "#/components/schemas/Object4"
    Object1: 
      allOf: 
        - $ref: "#/components/schemas/Object2" 
        - type: object
          required:
            - date
          properties:
            date:
              type: string
              format: date-time

    Object2: 
      # type: object # THIS LINE
      allOf: 
       - $ref: "#/components/schemas/Object3" 
       - $ref: "#/components/schemas/Object4"
```
