### ISSUE TITLE
Are there examples of using this package as a linter in GitHub CI/CD processes? 

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [byu-oit/openapi-enforcer#122]
Hi!
I've tried several libraries for OpenApi docs validating. And it seems that this  - is my favorite. It gives very similar result as the Swagger Editor with some additional notices. 
But could you tell me about using this package for GitHub CI/CD proposes?

**Comment by Gi60s** [comment]
I'm glad you like the library. We're in the process of creating version 2 that will have types (it's written in TypeScript) but will also have additional metadata and file and line numbers attached to each error, so you might find that useful too.

I have not seen this library used to validate your OpenAPI document as part of a CI/CD pipeline, but I'd imagine that isn't too hard to set up. Are you using Github actions for your CI/CD?

**Comment by Morgunov-Vitaly** [comment]
Hi! 
Yes, we use GitLab CI/CD

**Comment by Gi60s** [comment]
I don't know GitLab pipelines too well, but if all you need is an error code then you could write a script like this:

```js
Enforcer('spec/luckyads/openapi-dev.yaml', { fullResult: true })
  .then(function ({ error, warning }) {
    if (!error) {
       console.log('No errors with your document')
       process.exit(0) // success exit code
    } else if (warning) {
       console.warn(warning) // warn uses stderr so I think the text will show red, but it should allow you to continue
       process.exit(0)
    } else {
       console.error(error)
       process.exit(1) // any non-zero exit code is an error
    }
  })
```

**Comment by Morgunov-Vitaly** [comment]
Oh, thanks a lot! I'll tyr it.

**Comment by Gi60s** [comment]
Sounds great. Let me know if it ends up working.

**Comment by Gi60s** [comment]
Also, if you want to pass arguments into the script you can use [process.argv](https://nodejs.org/docs/latest/api/process.html#process_process_argv).
