### ISSUE TITLE
exclusiveMinimum and exclusiveMaximum as a number instead of boolean.

### ISSUE THREAD

**Issue by FVelasquezM** [byu-oit/openapi-enforcer#164]
As of [OAS 3.1.0](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0), `exclusiveMinimum` and `exclusiveMaximum` fields should be numeric instead of boolean, however, when loading from an OpenAPI document with numeric exclusiveMinimum or exclusiveMaximum:

```
 requestBody:
        content:
          application/json:
            schema:
              type: object
              required: ['amount']
              properties:
                amount:
                  type: number
                  exclusiveMinimum: 0
```

The following error is produced: 
```
Error: One or more errors exist in the OpenApi definition
 requestBody > content > application/json > schema > properties > amount > exclusiveMinimum
  Value must be a boolean. Received: 0
```

Are numeric `exclusiveMinimum` and `exclusiveMaximum` keywords not supported? Is it possible extend the enforcer in order to enforce numeric instead of boolean values for these fields?

**Comment by Gi60s** [comment]
Thanks for reaching out. The OpenAPI Enforcer doesn't support OAS 3.1.0 yet. I am working on a version 2 of the library that will support OAS 3.1.0 and future versions of the spec more readily.

Sorry it's not there yet.
