### ISSUE TITLE
Unexpected exception regarding callback definition

### ISSUE THREAD

**Issue by rafael-org** [byu-oit/openapi-enforcer#17]
We are starting a new API definition, and on it, we have a callback definition which is breaking the openapi-enforcer for incoming requests. It do not matter for this kind of validation, so perhaps it should simply be ignored.

What you think? Or am I doing something wrong?

The error message I get is: 
>   at: components > callbacks > subscription-event
>     Properties not allowed: type, {$request.body#/webhok/url}
>   at: paths > /subscriptions > post > callbacks > onEvent > type

I will attach our openapi file.

I found that this error originates from the validate.js on the line 157.

Any workarounds would be appreciated.

[openapi.yaml.txt](https://github.com/byu-oit/openapi-enforcer/files/3327872/openapi.yaml.txt)

**Comment by Gi60s** [comment]
Sorry for the slow response. I'm pretty sure that we're dealing with a bug in the enforcer. I might be able to have it fixed by the end of today. I'll keep you posted.

**Comment by rafael-org** [comment]
No problem. Thanks.

**Comment by Gi60s** [comment]
I've confirmed this as a bug that is fixed in PR #18 that has been merged to master and published to NPM under version `1.3.6`.

Thank you for the bug report.

**Comment by rafael-org** [comment]
Thanks. I am gonna try it right away.
