### ISSUE TITLE
Content type header versioning

### ISSUE THREAD

**Issue by Lakitna** [byu-oit/openapi-enforcer#20]
I've been using openapi-eforcer to lint my OAS and it's working great so far. It really improves the quality of my schemas and I'm even able to get everything without any warnings.

## Current situation

Except for one warning that has popped up due to the company switching to Zalando API guidelines. Specifically [this rule](https://opensource.zalando.com/restful-api-guidelines/#114) is not playing nice with openapi enforcer.

The rule basically states that versioning has to be done like this:

```yaml
      requestBody:
        required: true
        content:
          application/json;version=1:
            schema:
              $ref: '#/components/schemas/request'
          application/json:
            schema:
              $ref: '#/components/schemas/request'
      responses:
        '200':
          description: Successful operation
          content:
            application/json;version=1:
              schema:
                $ref: '#/components/schemas/response'
```

This throws the following warning:

```
WARNING
One or more warnings exist in the OpenApi definition
  at: paths > /foo/bar > post > responses > 200 > content > application/json;version=1
    Media type appears invalid
```

## Possible solution

Maybe add a way to change the acceptable media type headers. This will allow us to extend and limit the accepted media types.

Judging by https://github.com/byu-oit/openapi-enforcer/blob/master/src/enforcers/MediaType.js this is not possible at the moment. Also, I couldn't find it in the docs.

## Versions

OpenAPI enforcer: 1.3.4
OpenAPI: 3.0.2

**Comment by Gi60s** [comment]
I'm glad that you're finding this library useful.

Your content type `application/json;version=1` is valid but there is an omission in the regular expression that checks that. I'm going to create a PR that fixes this and I'll publish it today to NPM.

Also, by the comment: "I couldn't find it in the docs" do you mean that you couldn't find info about the MimeType component in the docs?

**Comment by Gi60s** [comment]
This has been fixed in PR #21 and published to NPM as version `1.4.1`.

**Comment by Lakitna** [comment]
Now that's a quick fix :)

> Also, by the comment: "I couldn't find it in the docs" do you mean that you couldn't find info about the MimeType component in the docs?

I was talking about how I couldn't find anything in the docs about changing the accepted content-types. But, to be fair, I didn't look very hard.

**Comment by Gi60s** [comment]
There isn't anything in the docs about changing the accepted content-types but as you said, it's not currently really implemented. That said though, there is a plugin architecture that allows you to modify the enforcer components that could probably be used to modify the regular expression that is used.

Glad this is working for you.
