### ISSUE TITLE
Enforcer always rejects request if request body is required

### ISSUE THREAD

**Issue by jaredkosanovic** [byu-oit/openapi-enforcer#24]
I ran into an issue when using the openapi-enforcer-middleware where my openAPI v3 spec had a required request body for a `POST`. The enforcer always rejected the request, regardless if the request contained a body:
```
Error: Request has one or more errors
  Missing required request body
```

**Comment by Gi60s** [comment]
Sorry for the slow response. I was out camping all last week and didn't have internet service. I haven't yet attempted to recreate this bug on my end, but I'll try that out. If you want to attach an Open API definition that displays this error then that could help, but your explanation seems pretty straight forward.

**Comment by Gi60s** [comment]
I am not seeing this error on my end. You mentioned that you're using the [openapi-enforcer-middleware](https://www.npmjs.com/package/openapi-enforcer-middleware) that does not parse the body. It only validates a parsed body. You can see in the [getting started server example in the middleware docs](https://byu-oit.github.io/openapi-enforcer-middleware/getting-started#server) that a JSON body parser middlware is added to Express prior to running the enforcer middleware.

Have you added the appropriate body parsing middleware?
