### ISSUE TITLE
Incorrect validation for OAuth client credential flow

### ISSUE THREAD

**Issue by equalspeterd** [byu-oit/openapi-enforcer#26]
During schema validation, the command `openapi-enforcer create-api <spec> <output>` throws the following exception:
```
    at: securitySchemes > myScheme > flows > clientCredentials
      Missing required property: refreshUrl
```
however, refreshUrl is not required in OAuth2 Flow object:
```
The URL to be used for obtaining refresh tokens. This MUST be in the form of a URL.
``` 
(note it is missing the typical **Required** annotation)

the `clientCredential` flow in fact, typically just requires a replay of the credential to the `tokenUrl`.

**Comment by Gi60s** [comment]
Thank you so much for the bug report. I've made the correction and published it to NPM as `openapi-enforcer@1.4.6`.
