### ISSUE TITLE
Mediatype enforcement doesn't include numbers in the vendor string

### ISSUE THREAD

**Issue by ethan92429** [byu-oit/openapi-enforcer#34]
Great tool! Thanks for making this!

We use MediaTypes to version our API and they looks something like: `application/vnd.onshape.v2+json` but your regex, `^(application|audio|example|font|image|message|model|multipart|text|video|x-\S+)\/(?:([a-z.\-]+)\+)?([a-z.\-]+)(?:; *(.+))?$` - [linked here](https://github.com/byu-oit/openapi-enforcer/blob/8fbe3b731852dab1ab9ca8532df4980ecdb016ca/src/enforcers/MediaType.js#L62) throws an error because the '2' is within the later part of the mediaType. Simply changing to: `^(application|audio|example|font|image|message|model|multipart|text|video|x-\S+)\/(?:([\w.\-]+)\+)?([\w.\-]+)(?:; *(.+))?$` would allow for numbers in those areas. I'll submit a pr

**Comment by Gi60s** [comment]
I'm glad you're using the tool and enjoying it.

This is a great bug catch. I've looked at your PR (#35) and it all looks good. I'll merge and leave a few more comments there.
