### ISSUE TITLE
Warning about format triggers other warnings

### ISSUE THREAD

**Issue by jcoyne** [byu-oit/openapi-enforcer#37]
I have this excerpt in my openapi.json:
```json
        "responses": {
          "201": {
            "description": "Virtual merge action started",
            "headers": {
              "Location": {
                "description": "the status of the action is found at this URI",
                "schema": {
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          },
        },
```

It's my understanding per https://swagger.io/docs/specification/data-models/data-types/#format that format is unconstrained:

>  format is an open value, so you can use any formats, even not those defined by the OpenAPI Specification, such as:  ...uri

So, I think these warnings are a bit too strict:
```
$ openapi-enforcer validate openapi.json

Document is valid but has one or more warnings.

One or more warnings exist in the OpenApi definition
  at: paths
    at: /virtual_objects > post > responses > 201
      at: headers > Location > schema > format
        Non standard format "uri" used for type "string"
      A 201 response for a POST request should return a location header (https://tools.ietf.org/html/rfc7231#section-4.3.3) and this is not documented in your OpenAPI document.
    at: /objects/{id}/publish > post > responses > 201
      at: headers > Location > schema > format
```

**Comment by Gi60s** [comment]
Hey @jcoyne. Thanks for the issue. This issue is fairly easy to resolve. See #36.

Also, if you have any other ideas or suggestions after looking at the solution for #36 please let me know. I'd love to hear them. Thanks.

**Comment by Gi60s** [comment]
I've decided that this is enough of a pain point for people that I added some functionality that allows you to control which warning codes you see. You can check out the documentation at https://byu-oit.github.io/openapi-enforcer/guide/exceptions. The changes are active on NPM with version `1.6.0`.
