### ISSUE TITLE
Header instead of headers in documentation

### ISSUE THREAD

**Issue by PalleZ** [byu-oit/openapi-enforcer#40]
According to documentation (https://byu-oit.github.io/openapi-enforcer/api/components/openapi ) there is a header property in Request parameter for OpenApi Request method but in reality it seems to be called headers.
Actually this seems to be a breaking change since this was working in an older version of openapi-enforcer. So behaviour has changed but documentation has not been updated.

**Comment by Gi60s** [comment]
Nice catch. Thank you for reporting the error in documentation.

This was a breaking change that occurred during the 0.x releases, happening on on [Dec 7 2018](https://github.com/byu-oit/openapi-enforcer/commit/5c124144ddf5092f53f25964f80487010bc0785b). The 1.x release came two weeks later on [Dec 21 2018](https://github.com/byu-oit/openapi-enforcer/commit/e0ed81145dbf0244026fc1625f7fc5e4d36c4964#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

I have updated the documentation to show the property is `headers`, not `header`.

Thank you, again.
