### ISSUE TITLE
False positive for Definition missing path parameters

### ISSUE THREAD

**Issue by jcoyne** [byu-oit/openapi-enforcer#47]
When I run my spec through the linter I get the following error:

```
One or more errors exist in the OpenApi definition
  at: paths
    at: /queues/{path}/{file}
      Path parameter definitions inconsistent
        at: get
          Definition missing path parameters: path, file
```

I'm having trouble finding where this is required by the spec.  Is it possible this shouldn't be alerting?

**Comment by Gi60s** [comment]
Help me to understand the question a bit better. Have you defined a path `/queues/{path}/{file}` that does not define parameters, specifically the path parameters?

I also could not find this clearly written in the spec, besides that in the parameters object all `path` parameters are supposed to be set to `required: true`:

https://swagger.io/specification/#parameterObject

> If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

Also, trying to define a path  `/queues/{path}/{file}` in the [online swagger editor](https://editor.swagger.io) without defining the parameters in the parameter array results in these errors:

- `Declared path parameter "path" needs to be defined as a path parameter at either the path or operation level`

- `Declared path parameter "file" needs to be defined as a path parameter at either the path or operation level`

Am I misunderstanding the question? You're OpenAPI document might help, or a portion of it, to understand better the question.

**Comment by jcoyne** [comment]
Okay, I've asked for clarification on the spec https://github.com/OAI/OpenAPI-Specification/issues/2079  It does seem a strong indicator of correctness that https://editor.swagger.io is following this convention too.

**Comment by Gi60s** [comment]
I'll close this issue for now, but I'm happy to reopen it if we find there is a need for change. Thank you.
