### ISSUE TITLE
Should allow whitepaces in base64 string

### ISSUE THREAD

**Issue by MaelPic** [byu-oit/openapi-enforcer#49]
Hello,
RFC 4648, which defines base64, says the following in section 3.3:

> Such specifications may instead state, as MIME
   does, that characters outside the base encoding alphabet should
   simply be ignored when interpreting data ("be liberal in what you
   accept").  Note that this means that any adjacent carriage return/
   line feed (CRLF) characters constitute "non-alphabet characters" and
   are ignored. 

It means that line returns, and more generally whitespaces, are allowed in base64 but should simply be ignored by the parser.
In consequence, openapi-enforcer should also ignored them, in my opinion.
Thank you,
Mael

**Comment by MaelPic** [comment]
In case you agree with previous statement, I made a PR: https://github.com/byu-oit/openapi-enforcer/pull/50
Thanks!

**Comment by Gi60s** [comment]
Wow! I never knew that. Very cool. Thanks for the reference. I'll check the PR.

**Comment by Gi60s** [comment]
OK, merged and published on NPM as version `1.6.6`. Thanks for the help.
