### ISSUE TITLE
Media Type - placeholder */*  : Media type appears invalid. [WMED001]

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer#53]
Hello, 

As explained in [Swagger docs](https://swagger.io/docs/specification/media-types/), we can use `*/*` if an response has multiple media types (depending of the context). For example, it is useful if we have [a static endpoint](https://expressjs.com/en/starter/static-files.html)

```js
app.use("/files", express.static(__dirname + "/someStaticFolder"));
```

that we will want to expose to users ( no `x-controller` and `x-operation` needed as express does the work for us ) : 

```yaml
paths:
  /files/{file}:
    parameters:
        - name: file
          in: path
          description: "The path to the file we want to access"
          example: "someFile.zip"
          required: true
          schema:
            type: string
    get:
      summary: "Download a stored file on the API"
      operationId: downloadFile
      tags:
        - guest
      responses:
        '200':
          description: "The file"
          content:
            '*/*':
              schema:
                type: string
                format: binary
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "../definitions.yaml#/components/schemas/ErrorObject"
```

However, `openapi-enforcer` doesn't like this way as it uses the following [regex](https://github.com/byu-oit/openapi-enforcer/blob/master/src/enforcers/MediaType.js#L65) : 

![image](https://user-images.githubusercontent.com/9306961/71587323-8003cc80-2b1d-11ea-9454-09c99c74cbe0.png)

Whereas others tools ( `redoc `and `@openapitools/openapi-generator-cli` )

![image](https://user-images.githubusercontent.com/9306961/71587679-f48b3b00-2b1e-11ea-8b5c-8bfd39beb0bb.png)

PS: I know we can disable warnings by `exceptionSkipCodes` option but I'm curious to see what you think about it

**Comment by Gi60s** [comment]
I think it makes sense that a `*/*` should not produce a warning. I do however think that this warning is still appropriate for other conditions that may cause it.

Do you agree?

**Comment by jy95** [comment]
It is up to you ;) 
The current behaviour is ok ( and follows RFC 6838 guidelines of the media types RFC ) : just I found curious that [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) and others doesn't have this kind of useful behaviour
