### ISSUE TITLE
Handle queryParameters first deserialization with qs ?

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer#56]
Hello,

As there is no consensus on seriliazation `style: deepObject explode:  true`  ( like explained [here](https://github.com/OAI/OpenAPI-Specification/issues/1706) ), some users cannot use the API as they think it would work.
Like explained this issue on the specs, many users uses [qs](https://www.npmjs.com/package/qs) under the hood so for example, if I have an endpoint like this : 

```yaml
  /api/exercises/{id}:
    parameters:
        - name: id
          in: path
          description: "The exercise ID"
          required: true
          schema:
            type: integer
        - name: includeOptions
          in: query
          description: "To include additional properties when fetching exercise"
          schema:
            $ref: "#/components/schemas/IncludeOptions"
components:
  schemas:
    IncludeOptions:
      type: object
      description: "To include additional properties when fetching exercise(s)"
      properties:
        includeCreator:
          type: boolean
          default: false
          description: "Must we include the creator of exercise(s) ?"
        includeMetrics:
          type: boolean
          default: true
          description: "Must we include the metrics of exercise(s) ?"
        includeDescription:
          type: boolean
          default: true
          description: "Must we include the description of exercise(s) ?"
        includeTags:
          type: boolean
          default: true
          description: "Must we include the tags of exercise(s) ?"
```

And simulate a request inside a unit test done with [supertest](https://www.npmjs.com/package/supertest)

```js
const check = await request
            .get("/api/exercises/42")
            .set('Authorization', 'bearer ' + JWT_TOKEN)
            .query('includeOptions%5BincludeCreator%5D=true')
            .query('includeOptions%5BincludeMetrics%5D=false')
            .query('includeOptions%5BincludeDescription%5D=false')
            .query('includeOptions%5BincludeTags%5D=false')
            .send();

expect(check.status).toBe(200);
```

gives me an 400 error with the following message : 

```
Request has one or more errors
  In query parameters
    Received unexpected parameters: includeOptions[includeCreator], includeOptions[includeMetrics], includeOptions[includeDescription], includeOptions[includeTags]
      Possible causes
        In query parameter "includeOptions"
          Unable to parse value
            The value is not formatted properly
```

If you need the code to generate the query parameters

```js
var qs = require('qs');
var obj  = {
    "includeOptions": {
        "includeCreator" : true,
        "includeMetrics" : false,
        "includeDescription" : false,
        "includeTags": false,
    }
}
var str = qs.stringify(obj);
console.log(str);
```

**Comment by jy95** [comment]
Currently, I am using this workaround ( that has the drawback of disable openapi-enforcer type deserialization ) : 

```js
module.exports = function () {
    return (req, res, next) => {
        // After qs (or querystring ), we may need to do additional stuff
        if (Object.keys(req.query).length > 0) {
            // disable openapi-enforcer validation of query parameters
            req.url = req.url.split("?")[0];
            req.originalUrl = req.originalUrl.split("?")[0];
        }
        next();
    }
};
```

**Comment by Gi60s** [comment]
Give me a little more context for where this problem is originating. Are you using the [openapi-enforcer-middleware](https://www.npmjs.com/package/openapi-enforcer-middleware) or are you using your own request handler intermediary?

Do you have a repository I could look at to understand this problem better?

**Comment by jy95** [comment]
I am using the openapi-enforcer-middleware. 

I don't have one if I have to create one, it will be similar to the [one](https://github.com/jy95/demoBug) I created to showcase some bugs previously , using the part of OAS and the supertest example  I give above

**Comment by jy95** [comment]
I am using the openapi-enforcer-middleware.
I reused the previously used [minimal demo project](https://github.com/jy95/demoBug) to showcase this bug

**Comment by Gi60s** [comment]
OK, I think I've got this figured out. The parameter parser needs to `decodeURIComponent` for those query parameters. If you take the same test as before but decode the query parameters it works.

I've found a spot where I think it makes sense to add that decode, but I'm going to write some tests to make sure it doesn't affect other things.

The below code seems to work. Notice that I removed the `%05B` and `%05D`.

```js
const check = await request
            .get("/api/exercises/42")
            .set('Authorization', 'bearer ' + JWT_TOKEN)
            .query('includeOptions[includeCreator]=true')
            .query('includeOptions[includeMetrics]=false')
            .query('includeOptions[includeDescription]=false')
            .query('includeOptions[includeTags]=false')
            .send();

expect(check.status).toBe(200);
```

Let me know if you're seeing other behavior. I'll start the fix.

**Comment by jy95** [comment]
I think you can reuse this function to detect that on [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent) : 

```js
function containsEncodedComponents(x) {
  // ie ?,=,&,/ etc
  return (decodeURI(x) !== decodeURIComponent(x));
}
```

A few examples were given : 

```js
console.log(containsEncodedComponents('%3Fx%3Dtest')); // ?x=test
// expected output: true

console.log(containsEncodedComponents('%D1%88%D0%B5%D0%BB%D0%BB%D1%8B')); // шеллы
// expected output: false
```

**Comment by Gi60s** [comment]
Fix is in PR #57. Published to NPM as version `1.8.1`.

**Comment by jy95** [comment]
Thanks : it that expected ?

![image](https://user-images.githubusercontent.com/9306961/72560582-a0ff4800-38a7-11ea-9a17-d4166eae45e9.png)

URL : /api/users?metadata%5Bsize%5D=10&metadata%5Bpage%5D=1

**Comment by Gi60s** [comment]
Whew. You had me worried.

**Comment by jy95** [comment]
Still testing if I don't find a corner case ... will tell you if I found something

**Comment by jy95** [comment]
Did you test the combination `style: deepObject` with `explode: true` ?

**Comment by jy95** [comment]
From what I test : 
- objects ( like my example) works now with `deepObject`
- arrays in url done by [qs](https://www.npmjs.com/package/qs) seems not to work

`http://127.0.0.1:57185/api/tags?state=pending&tags_ids[]=1&tags_ids[]=2&categories_ids[]=1&title=hero`

gives : 

```
Request has one or more errors
  In query parameters
    Received unexpected parameters: tags_ids[], categories_ids[]
```

Any ideas ?

**Comment by Gi60s** [comment]
Write your parameters like this: `http://127.0.0.1:57185/api/tags?state=pending&tags_ids=1&tags_ids=2&categories_ids=1&title=hero`

**Comment by jy95** [comment]
Thanks : It seems my friend uses [axios](https://github.com/axios/axios) that has this default behaviour ...

```
  // `paramsSerializer` is an optional function in charge of serializing `params`
  // (e.g. https://www.npmjs.com/package/qs, http://api.jquery.com/jquery.param/)
  paramsSerializer: function (params) {
    return Qs.stringify(params, {arrayFormat: 'brackets'})
  },
```
If I follow your requirements, the [`arrayFormat: 'repeat`](https://github.com/ljharb/qs#stringifying) option should work for that : 

```js
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b&a=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })
// 'a=b,c'
```

PS: Honestly, handle query parameters is a nightmare and I don know how you survived from it ^^

**Comment by Gi60s** [comment]
I'm glad it's working. That interesting to know about axios using brackets as the default format. I wasn't aware of that.
