### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by mattiasrunge** [byu-oit/openapi-enforcer#7]
Hi,

I am trying to use the openapi-enforcer since it matches what I need well but am having lots of trouble with the current stable version so have tried the development branches. The components-before-validators works best after a round of patching but it seems that there are bigger holes still, like the discriminator work.

What is the status of this branch and do you know when it might be released?

Thank you!
Mattias

**Comment by Gi60s** [comment]
Mattias,

Sorry to be so slow in responding to this message. There have been some substantial updates in the last month. The code is reaching a pretty stable place and discriminators are working. See these docs: https://github.com/byu-oit/openapi-enforcer/blob/master/docs/components/schema.md#schemaprototypediscriminate

I'll be releasing a more finalized documentation for the main README.md file in the next day or so.

Once again, sorry for the slow response.

**Comment by Gi60s** [comment]
Sorry to spam you with messages. I've been waiting on the NPM 1.x release. I'll probably push that out tomorrow too.
