### ISSUE TITLE
Discriminator mappings residing in external files cannot be resolved

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [byu-oit/openapi-enforcer#71]
I have a spec with the following discriminator mappings:

```
discriminator:
  propertyName: '_type'
  mapping:
    dog: '../model/dog.yaml'
    cat: '../model/cat.yaml"
```
When I run this spec through validation, I encounter the following error:

> Reference cannot be resolved: ../model/dog.yaml. If you are using multiple files to define your OpenAPI document then this may be a limitation of the original dereference function. You can try the custom reference parser (in beta) to see if this resolves the issue.

However, if I describe the discriminator mappings to models defined with the spec such as 

```
 mapping:
    dog: '#/components/schemas/dog'
    cat: '#/components/schemas/cat'
```

I do not encounter these errors.  Looks like there was a fix in version 1.10.0 to deal with mappings defined outside of the spec but this appear to still be a problem.

**Comment by Gi60s** [comment]
Are you using the [useNewRefParser option](https://byu-oit.github.io/openapi-enforcer/api/openapi-enforcer#enforcerconfig)?

The original ref parser is unable to link mappings to their appropriate objects so I had to write a custom ref parser.

**Comment by Klaus-Nji-sp** [comment]
Interesting..... 

No I was not using that option.  Thanks for pointing me towards that direction.   I should have paid close attention to the literature.

I do see that this feature is in beta but will report this problem anyway.  

This option does resolve the issue of not being able to resolve discriminator mappings in external files.  Should this new parser not also support the same functionality in the original parser where discriminator mappings defined with #/components can be resolved?

**Comment by Gi60s** [comment]
The new parser should work for that too. Can you give me a full `openapi.yml` file to see this not working? I can use that to make sure I'm fixing this particular bug.

Thank you.

**Comment by Klaus-Nji-sp** [comment]
Ok let me investigate further.  I wonder if it has to do with the fact that the base spec is where the components and schemas are defined while I am referencing these components outside of the base spec.  Let me fully understand the problem and will update this issue.  

Thanks for the quick responses.

**Comment by Klaus-Nji-sp** [comment]
Ok, here are some specs:

```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
paths: 
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A pet
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'dog-schema.yml'
                  - $ref: 'cat-schema.yml'
                discriminator:
                  propertyName: petType
                  mapping:
                    dog: 'dog-schema.yml'
                    cat: 'cat-schema.yml'
components:
  schemas:
    Dog:
      $ref: 'dog-schema.yml'
    Cat:
      $ref: 'cat-schema.yml'    
```

With `dog-schema.yml` and `cat-schema.yml` as follows:

```
type: object
required:
  - id
  - name
  - petType
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  petType:
    type: string
```
If run the spec through validation with  

`Enforcer.config.useNewRefParser = true;` I am getting this error:

>   Missing required "openapi" or "swagger" property

Now, I did not expect this error.  Instead, I was hoping the new parser option will be able to resolve the above.  It did in my real world example, even though I have a deeper nesting.  

Anyways, the issue I run into now, is that with the newRefParser option turned on, the previous mapping which used `schema` definitions in the `component` section of the root schema could no longer be validated.

**Comment by Gi60s** [comment]
Taking the example you've given me I see this error:

```
[ EnforcerException: One or more errors exist in the OpenApi definition
    at: paths
      at: /pets/{petId} > get > responses > 200 > content > application/json > schema > discriminator > mapping
        at: dog
          Reference cannot be resolved: dog-schema.yml
        at: cat
          Reference cannot be resolved: cat-schema.yml ]
```

The reason it fails to resolve is that the mapping values `dog-schema.yml` and `cat-schema.yml` can be one of three things:

1. A path to another file (and potentially a path within that file)
2. A path within the current file
3. The name of a schema

This 3rd item is where the snag hits. The enforcer doesn't know if `dog-schema.yml` is a path or a named schema within the components. Currently the logic identifies if the value has an HTTP path or a forward slash (`/`) which would indicate a path. I could allow it to look for dots (`.`) too to indicate a path, but I worry that would possibly exclude some weirdly named schemas that have dots in them.

To resolve this mapping problem you can do one of three things:

1. Add `./` to signify a path:

    ```yml
    mapping:
      dog: './dog-schema.yml'
      cat: './cat-schema.yml'
    ```

2. Use the schema name (as is found in `components/schemas`):

    ```yml
    mapping:
      dog: 'Dog'
      cat: 'Cat'
    ```

3. Use the local ref path:

    ```yml
    mapping:
      dog: '#/components/schemas/Dog'
      cat: '#/components/schemas/Cat'
    ```

**Comment by Klaus-Nji-sp** [comment]
Makes sense. I will try to understand why my situation does not resolve components with newRefParser turned on.  With the simple case where spec and schemas are in the same directory, I do not see the problem if I append the './' infront of the file name.  However with a deep directory structure, there appears to be a problem.

Certainly agreed with being cautious of dealing with namings which begin with an '.'.  However, since other areas of the spec allow for specifying a file in the same location without starting with './' would you not want to be consistent?

**Comment by Gi60s** [comment]
That is a valid argument as far as consistency goes. I'll think about that and potential solutions.

Can you share a repo link for some deep directory structure that doesn't work?

**Comment by Klaus-Nji-sp** [comment]
OK give me sometime next week.  Let me ensure it is not my problem.

**Comment by Gi60s** [comment]
Any update on this?

Thanks for checking.

**Comment by Klaus-Nji-sp** [comment]
Sorry, I have not had a moment to duplicate the problem.  I have since delegate this work to another developer.  Please give me a week or so.

**Comment by Gi60s** [comment]
I'm going to mark this as closed. If you find out that the issue does still exist, please let me know.
