### ISSUE TITLE
[Publish] Possible to have access to openapi-enforcer-cli source repository?

### ISSUE THREAD

**Issue by madarche** [byu-oit/openapi-enforcer#73]
Hello,

Would it be possible to have access to the source repository of the package https://www.npmjs.com/package/openapi-enforcer-cli please?

Thanks!

**Comment by Gi60s** [comment]
Yes, I've made it public. It's very rough edged right now and I'm happy to receive PRs.

https://github.com/byu-oit/openapi-enforcer-cli

**Comment by madarche** [comment]
Thanks a lot @Gi60s!
