### ISSUE TITLE
Bug: Enforcer options object is altered

### ISSUE THREAD

**Issue by Lakitna** [byu-oit/openapi-enforcer#74]
This seems to be an issue since [this line was changed](https://github.com/byu-oit/openapi-enforcer/blame/ab64cdd63e1648e2543a510162328fa5ec9fc6b2/src/super.js#L91).

When running the enforcer multiple times with the same options object the second pass will throw an error:

```
options.exceptionSkipCodes.reduce is not a function
```

What seems to happen is that in the first pass `options.exceptionSkipCodes` is changed from an array to an object. This change is a side effect that causes the error to be thrown on the second pass where it essentially tries to do `{}.reduce()` instead of `[].reduce()`.

It looks like the same side effect is created for `options.exceptionEscalateCodes` [on this line](https://github.com/byu-oit/openapi-enforcer/blame/ab64cdd63e1648e2543a510162328fa5ec9fc6b2/src/super.js#L97)

I've solved this for now by cloning my options object before passing it to the enforcer.

**Comment by Gi60s** [comment]
Thanks for the bug report and awesome research identifying the problem. I've made a fix in `1.10.3` and have published it to NPM.
