### ISSUE TITLE
unexpected discriminator exception for schema `anyOf`

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer#8]
I have a use case with openapi-enforcer-middleware where I am getting this particular exception unexpectedly https://github.com/byu-oit/openapi-enforcer/blob/d3a2f465cad891b028874a7be69142e0b1036c89/src/schema/deserialize.js#L51-L54
I posted the issue in this repo because the exception message comes from this package.

This occurs when I try to make a request to a `PATCH` endpoint where the request body is used to update one or more properties of the user.

I am trying to use `anyOf` in order to get validation behavior that will only accept a request body if it has *at least one* of the properties `password`, `about`, or `displayName`.

Following the example here, https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#anyof, it should be possible to have `anyOf` without requiring a discriminator. However, openapi-enforcer code appears to require a discriminator whenever there is an `anyOf` (line 51 and 53 above).

so it seems there should be a code path where it is acceptable to NOT have a discriminator with a `anyOf`.

more description of discriminator is here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#discriminator-object

My relevant oas:
```
      requestBody:
        description: The user updates
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - type: object
                  properties:
                    password:
                      type: string
                      minLength: 3
                      maxLength: 20
                - type: object
                  properties:
                    about:
                      type: string
                      minLength: 0
                      maxLength: 255
                - type: object
                  properties:
                    displayName:
                      type: string
                      minLength: 3
                      maxLength: 20
```

**Comment by Gi60s** [comment]
Thanks for helping make the software better. You are correct. I'll see if I can get this working today.

**Comment by Gi60s** [comment]
Version 1.2.4 fixes this issue and that is now available on NPM.

Note that this is still not perfect. It has to make an educated guess because by default `additionalProperties` is `true` meaning that for your example if a request came in with the properties `password` and `about` then it wouldn't know which schema to deserialize against. You could set `additionalProperties` to `false` to fix that possibility.
