### ISSUE TITLE
Required schema properties possibly not matching spec

### ISSUE THREAD

**Issue by franklin-ross** [byu-oit/openapi-enforcer#82]
Howdy! I'm getting some errors when I try to load our contracts up with `openapi-enforcer`, and I'm a bit confused, because we can load them successfully into various other validators and tools. The error I'm getting (for hundreds of routes) looks something like this:

```
EnforcerException: One or more errors exist in the OpenApi definition
    at: paths
      at: /things > get > responses > 200 > content > application/json
        at: schema > items
          Properties not allowed: properties, required
          Missing required property: type
```

It looks like it's expecting a different object at that point, or possibly just that is being overly strict on it's requirements? I'm not sure whether this is related, but it looks like [type, at least, should not be required](https://github.com/OAI/OpenAPI-Specification/issues/1657).

Is there wriggle room in the spec for our contracts to be valid for some validators and not others? Or does that look like a bug in our contracts?

Thanks for the help!

**Comment by Gi60s** [comment]
I'm going to close this due to inactivity. Let me know if I can help in the future.
