### ISSUE TITLE
schema.deserialize does not exist when using parameter component

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer#9]
query parameters like `limit` and `offset` are common for collection endpoints like `GET /messages?limit=100&offset=100`. I would like these query parameters to be re-usable components because i have multiple collection endpoints which provide the same query parameter options.

I have defined `limit` and `offset` as re-usable components located at `"#/components/parameters/limitParam` and `#/components/parameters/offsetParam`. It appears due to OAS syntax rules that I must write my OAS like so:
```yaml
components:
  parameters:
    limitParam:
      name: limit
      in: query
      description: Number of items to return
      required: false
      schema:
        type: integer
        minimum: 0
        default: 100
    offsetParam:
      name: offset
      in: query
      description: Number of items to skip
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0

...

paths:
  /messages:
    get:
      summary: Get a list of messages
      operationId: getMessages
      x-controller: messages
      x-operation: getMessages
      tags:
        - Messages
      parameters:
        - in: query
          name: offset
          schema:
            $ref: "#/components/parameters/offsetParam"
        - in: query
          name: limit
          schema:
            $ref: "#/components/parameters/limitParam"

...

```
When openapi-enforcer hits a particular line in `Operation.js` `deserializeAndValidate`, **the `schema.deserialize` method does not exist**. This appears to be due to using `$ref` above because `offsetParam` has its own `schema` and there *is* a nested deserialize method at `schema.schema.deserialize`

<img width="799" alt="Screen Shot 2019-05-15 at 3 45 33 AM" src="https://user-images.githubusercontent.com/8955144/57758823-93654300-76c6-11e9-940c-c85cea4bcb9c.png">

As a possible fix, It seems the code could be adjusted to 
```js
    if (!data.error) data = (schema.deserialize && schema.deserialize(data.value)) || schema.schema.deserialize(data.value);
```
however, i'm still wondering if there is another way to write the OAS syntax so that there is not a nested `schema.schema.deserialize` while still using the component parameters

A workaround is to just not use $ref to the component parameters section and instead write the schema inline.

**Comment by thurt** [comment]
A second sub-issue:
after adjusting the code to use the possible fix above, i have noticed that I'm getting a validation error for these query parameters. i believe this is because query parameters always come in as strings, but I would ideally like them to be cast to integer so they can be validated according to rules like `minimum` and `maximum`

**Comment by Gi60s** [comment]
I believe the problem here is that your OAS document isn't structured properly. For example...

```yml
components:
  parameters:
    limitParam:
      name: limit
      in: query
      description: Number of items to return
      required: false
      schema:
        type: integer
        minimum: 0
        default: 100

...

paths:
  /messages:
    get:
      summary: Get a list of messages
      operationId: getMessages
      x-controller: messages
      x-operation: getMessages
      tags:
        - Messages
      parameters:
        - in: query
          name: limit
          schema:
            $ref: "#/components/parameters/limitParam"
```

Dereferences to:

```yml
paths:
  /messages:
    get:
      summary: Get a list of messages
      operationId: getMessages
      x-controller: messages
      x-operation: getMessages
      tags:
        - Messages
      parameters:
        - in: query
          name: limit
          schema:
            name: limit
            in: query
            description: Number of items to return
            required: false
            schema:
              type: integer
              minimum: 0
              default: 100
```

Shouldn't your OAS document look something like this for parameter reuse?

```yml
openapi: 3.0.0
info:
  title: ''
  version: '1.0'
paths:
  /:
    get:
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        default:
          description: OK
components:
  parameters:
    limit:
      in: query
      name: limit
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 100
```

Once your document is set up properly it will correctly deserialize your query parameters (converting them to numbers).

Also, as a side note, you don't need both an `operationId` and an `x-operation`. Either can be provided, but if both are provided then I believe the `x-operation` is used.

**Comment by thurt** [comment]
I changed my path parameters to
```yaml
      parameters:
        - $ref: "#/components/parameters/limitParam"
        - $ref: "#/components/parameters/offsetParam"
```
and both issues are resolved now. Thanks again!
