### ISSUE TITLE
How do I validate a response confirms with a schema?

### ISSUE THREAD

**Issue by jamescrowley** [byu-oit/openapi-enforcer#90]
Apologies if this is staring me in the face somewhere, but I can't see how to validate that an API response conforms to the schema?

While I can successfully validate an incoming request against a schema, I couldn't see anything in the docs about responses - but the description on https://openapi.tools/#data-validators suggested that it was possible? Thanks

**Comment by Gi60s** [comment]
Not a problem at all. Just the fact that you're having a hard time finding that in the documentation is an indicator that I need to clarify it, so thank you for asking. I'll work on getting the docs update too (hopefully sooner than later).

There are multiple ways to validate values against schemas.

1. If you don't have the operation object then you could use this https://byu-oit.github.io/openapi-enforcer/api/components/openapi#request to get an object that has both an `operation` and `response` property. You could use the `response` property to validate the response. This will validate mime types, status codes, headers, and body.

2. If you do have the operation object then you could use this: https://byu-oit.github.io/openapi-enforcer/api/components/operation#response

3. If you already have a schema and just want to validate a value against it:

    - Start with this documentation: https://byu-oit.github.io/openapi-enforcer/api/components/schema#validate

    - Assuming you've validated your spec using https://byu-oit.github.io/openapi-enforcer/api/openapi-enforcer#enforcer then you'll also need to traverse the returned object to get the schema before you can validate a value against it, like this:
        ```js
        Enforcer('/dir/openapi.yml').then(openapi => {
          openapi.components.schemas.mySchema.validate('some value')
        })
        ```

Feel free to ask any other questions. I'll keep this issue open for at least a few days or until you've verified with me that you have figured it out. Have a great day.

**Comment by freerider7777** [comment]
@Gi60s It's not easy to get from the docs how to:
1. load a yaml file
2. construct a request object
3. validate the request by OpenAPI schema

It's not obvious that we need to get a 'value' field of "await Enforcer"

**Comment by Gi60s** [comment]
@freerider7777 I'm not sure if this will fit what you're trying to do, but have you looked at the 
[Enforcer Middleware](https://www.npmjs.com/package/openapi-enforcer-middleware) or the [Enforcer Lambda](https://www.npmjs.com/package/openapi-enforcer-lambda)?

As for your three points:

1. The only way to load currently is here: https://byu-oit.github.io/openapi-enforcer/api/opening#enforcer. Version 2 is well under way and will provide additional options for loading.
2. See https://byu-oit.github.io/openapi-enforcer/api/components/openapi#request
3. Same as above.

I'm actively reworking the docs with an emphasis on better guides and examples. It might be a few weeks before those are up.

Thanks for the feedback and let me know if there is anything else.

**Comment by freerider7777** [comment]
@Gi60s Of course I know the Middleware :) (and wrote some issues [https://github.com/byu-oit/openapi-enforcer-middleware/issues/60](https://github.com/byu-oit/openapi-enforcer-middleware/issues/60) )
I have a low-level http handling service (with http.createServer(processRequest) ) and don't want to switch to express for now...

1. yes
2. yes
3. yes
but I mean it's not clear from the docs how to link 1. and 2. - only the sample from @jamescrowley helped me ([https://github.com/byu-oit/openapi-enforcer/issues/90#issuecomment-711598228](https://github.com/byu-oit/openapi-enforcer/issues/90#issuecomment-711598228)) that we need to take the **value** field and call **request** from it.

Anyway thanks for this library - works very well :)

**Comment by Gi60s** [comment]
Thanks for the feedback. I'll make sure this gets into the docs.
