### ISSUE TITLE
Just Saying Hello

### ISSUE THREAD

**Issue by kinlane** [byu-oit/openapi-enforcer#91]
Not an issue, but this came up in a random search, and so happy to see it is still active after first hearing about it on campus during the regular gathering!

**Comment by Gi60s** [comment]
Hey Kin. It's good to hear from you.

I saw your recent tweet as you were trying to tell your dog Poppy that you couldn't take her outside because you had a meeting. What a cute dog.

I'm glad it's active too. It's nice to see people using something that you helped create.
