### ISSUE TITLE
allow implicit type object

### ISSUE THREAD

**Issue by delanym** [byu-oit/openapi-enforcer#92]
There's an issue where the tool requires specifying type object. Implicit type object gives

>     Properties not allowed: properties, required
>     Missing required property: type
>

_Originally posted by @delanym in https://github.com/byu-oit/openapi-enforcer/issues/86#issuecomment-720763704_

**Comment by delanym** [comment]
It is possible to allow configuring this as a warning, and/or assuming everything is an object unless specified?

The thing if I use redoc-cli, it leaves references intact, which then break in the HTML. So openapi-enforcer is the only way I have of dereferencing a schema.

**Comment by Gi60s** [comment]
I've made a fix for this with PR #93 and published to NPM as `1.12.0`.

You can see the description of what changed in the CHANGELOG.md or by lookin at PR #93.
