### ISSUE TITLE
redoc no longer works

### ISSUE THREAD

**Issue by delanym** [byu-oit/openapi-enforcer#94]
`openapi-enforcer docs-build e.json e.html`

The output is "Built successfully" but no file is created.

CLI v0.3.5
OpenAPI Enforcer v1.12.0

**Comment by Gi60s** [comment]
LOL. That's rich. `"Build successfully"`. Apparently not. I'll take a look.

**Comment by Gi60s** [comment]
OK, this is now working in CLI v0.3.6 and has been published to NPM.

Thanks for the bug report.
