### ISSUE TITLE
Expose matched operations on validation errors

### ISSUE THREAD

**Issue by jankuca** [byu-oit/openapi-enforcer#95]
When there is an error (exception) returned from `openApi.request()` complaining about invalid parameters, it would be very useful to know which operation was matched by the request and validated against.

**Comment by Gi60s** [comment]
I've published a fix to NPM as version `1.12.1` that should get you what you are looking for. 

The exception object will now have some helpful properties on it in the case of an exception. You can read more about it in the documentation at https://byu-oit.github.io/openapi-enforcer/api/components/openapi#request at the end of the **Returns** subsection.

Thanks for the request. This is a valuable improvement.

**Comment by jankuca** [comment]
Thanks a lot! This should work for me.
